### ISSUE TITLE
Grid "NOT DONE YET"

### ISSUE THREAD

**Issue by AhmedSafi97** [G8-Summary/BEM-Accessibility-flexVSgrid-important_Animation#2]
> Flexbox is made for one dimensional layouts and Grid is made for two dimensional layouts.

![](https://hackernoon.com/hn-images/1*AxItLokVtaF56WMo_ZF6Pw.png)

- Turn any HTML element into a grid container by setting its display property to grid. 
``` CSS
 .container {
    display: grid;
  }
```

- To add some columns to the grid, use the grid-template-columns property on a grid container.
``` CSS
.container {
  display: grid;
  grid-template-columns: 50px 50px;
}
```

- To add some rows to the grid, use the grid-template-rows property on a grid container.
``` CSS
.container {
  display: grid;
  grid-template-rows: 50px 50px;
}
```
- You can use absolute and relative units like px and em in CSS Grid to define the size of rows and columns. You can use these as well:
`fr:` `sets the column or row to a fraction of the available space,`
`auto:` `sets the column or row to the width or height of its content automatically,`
`%:` `adjusts the column or row to the percent width of its container.`

- 1. To add a gap between the rows, use the grid-row-gap property
  2. To add a gap between the columns, use the grid-column-gap property
  3. grid-gap is a shorthand property for grid-row-gap and grid-column-gap
```CSS
  .container {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr 1fr;
    /* grid-row-gap: 10px;
    grid-column-gap: 15px; */
    grid-gap: 10px 15px;
  }
```
